name: Node.js CI và Triển khai

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./source
          npm ci
          npm run build --if-present
      - name: Build and deploy to dev
        if: github.ref == 'refs/heads/dev'
        run: |
          # Thực hiện các bước cần thiết để xây dựng ứng dụng cho môi trường prod
          # Ví dụ: npm install, npm run build

          # Di chuyển đến thư mục muốn triển khai (prod)
          mkdir -p dev
          cp -R ./source/* ./dev
          cd ./dev
          - name: Deploy Page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            destination_dir: dev
            publish_branch: gh-pages
            keep_files: true
          
      - name: Build and deploy to prod
        if: github.ref == 'refs/heads/main'
        run: |
          # Thực hiện các bước cần thiết để xây dựng ứng dụng cho môi trường prod
          # Ví dụ: npm install, npm run build

          # Di chuyển đến thư mục muốn triển khai (prod)
          mkdir -p prod
          cp -R ./source/* ./prod
          cd ./prod
          - name: Deploy Page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            destination_dir: prod
            publish_branch: gh-pages
            keep_files: true