name: Node.js CI và Triển khai

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./source
          npm ci
          npm run build --if-present
      - name: Deploy Page
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prod    # Thư mục chứa nội dung cần triển khai
          destination_dir: .     # Thư mục đích trên GitHub Pages
          publish_branch: gh-pages
          keep_files: true