name: Node.js CI và Triển khai

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy to dev
        if: github.ref == 'refs/heads/dev'
        run: |
          # Thực hiện các bước cần thiết để xây dựng ứng dụng cho môi trường dev
          # Ví dụ: npm install, npm run build

          # Di chuyển đến thư mục muốn triển khai (dev)
          mkdir -p dev
          cd ./dev

          # Khởi tạo và cấu hình GitHub Pages trong thư mục dev
          git init
          git config user.name "son17112001"
          git config user.email "son17112001@gmail.com"

          # Add, commit và push code lên nhánh gh-pages
          git add .
          git commit -m "Deploy to dev branch"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
          
      - name: Build and deploy to prod
        if: github.ref == 'refs/heads/main'
        run: |
          # Thực hiện các bước cần thiết để xây dựng ứng dụng cho môi trường prod
          # Ví dụ: npm install, npm run build

          # Di chuyển đến thư mục muốn triển khai (prod)
          mkdir -p prod
          cp -R ./source/* ./prod
          cd ./prod

          # Khởi tạo và cấu hình GitHub Pages trong thư mục prod
          git init
          git config user.name "son17112001"
          git config user.email "son17112001@gmail.com"

          # Add, commit và push code lên nhánh gh-pages
          git add .
          git commit -m "Deploy to prod branch"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages